spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/dorm_repair?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: Gq39k1oP17
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

mybatis:
    mapper-locations: classpath:com/dorm/mapper/*.xml
    type-aliases-package: com.example.demo.entity
    configuration:
      map-underscore-to-camel-case: true

server:
  port: 8081
  address: 127.0.0.1

user:
  id: 3225004433
  name:
  password:
  role:
  dormBuilding:
  roomNumber:

jwt:
  secretkey: Gq39k1Op05

logging:
  level:
    root: INFO
    com.example.demo: DEBUG

